### ISSUE TITLE
Implement printing of relevant information

### ISSUE THREAD

**Issue by ninsbl** [HamedElgizery/grass-addons#4]
What I think could be different information that should be possible to print to user are:

- [x] current eodag configuration (and file location)
- [x] configuration of a chosen provider (e.g. when print option and provider option are given)
- [x] available providers
- [x] available providers for a chosen product (if only a product is chosen)
- [x] available products
- [x] available products of a chosen provider (e.g. when print option and provider option are given)
- [x] queryables / metadata of product types (requires both provider and product option).

There may be more.

So a `print` option may make sense with possible answers for example: `configuration,provider,product,product_metadata`

Printable data has different structure / complexity (can be a simple list where plain output would be sufficient or a hirarchical structure (e.g. product metadata) where JSON output would be more appropriate or table like output (as in i.sentinel.download for example). 

Printing is a next step when basic query and download functionality is more mature...

**Comment by lucadelu** [comment]
Yeah, I support it especially the last sentence first query and download working well

**Comment by HamedElgizery** [comment]
The last 5 tasks are addressed here https://github.com/HamedElgizery/grass-addons/pull/15.

EDIT: First two tasks are now addressed as well, but without printing the config file location.
Because apparently eodag always uses the config file in the default location, and when another config file is provided by the user, it just overrides the main file with it (for the current session)... and it keeps rest of the providers configurations.

**Comment by veroandreo** [comment]
This one is complete AFAIU. Shall we close it?

**Comment by HamedElgizery** [comment]
> This one is complete AFAIU. Shall we close it?

I think so.
